name: Trigger For eConnect Repo

on:
  push:
    branches:
      - main
      - develop
      - build/*
  pull_request:
    branches:
      - main
      - develop
      - build/*

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Send repository dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: zivevo/eConnect
          event-type: trigger-gitflow
          token: ${{ secrets.ACCESS_TOKEN }}